import React from 'react';
import ExportBakerCredentials from '~/components/ExportBakerCredentials';
import { MakeOptional, PropsOf } from '~/utils/types';

type Props = MakeOptional<
    Omit<PropsOf<typeof ExportBakerCredentials>, 'children'>,
    'accountAddress' | 'bakerKeys'
>;

export default function ExportBakerKeys({
    accountAddress,
    bakerKeys,
    ...props
}: Props) {
    if (!accountAddress) {
        return null;
    }

    if (!bakerKeys) {
        return <p>Generating keys...</p>;
    }

    return (
        <ExportBakerCredentials
            accountAddress={accountAddress}
            bakerKeys={bakerKeys}
            {...props}
        >
            <p className="mT0">
                Your baker keys have been generated, and the public keys can be
                seen to the left.
            </p>
            <p>
                Make sure to export and backup your baker credentials, as this
                will be the only chance to export them.
            </p>
            <p>
                Baker credentials are used by the concordium node for baking and
                contains private keys, which should only be transferred on a
                secure channel.
            </p>
            <p>
                If the baker credentials are lost or compromised, new ones
                should be generated by updating baker keys.
            </p>
        </ExportBakerCredentials>
    );
}
