name: Concordium desktop wallet release

on:
  push:
    tags:
      - 'desktop-wallet/*.*.*-stagenet'
      - 'desktop-wallet/*.*.*-testnet'
      - 'desktop-wallet/*.*.*-mainnet'

env:
  WASM-PACK_VERSION: "v0.13.1"
  NODE_VERSION: "18.20.7"
  RUST_VERSION: "1.74.1"
  PYTHON_VERSION: "3.13.1"
  COREPACK_ENABLE_DOWNLOAD_PROMPT: "0"

jobs:
  metadata:
    name: Check version and prepare metadata
    runs-on: ubuntu-latest
    outputs:
      TARGET_NET: ${{ steps.target_net.outputs.TARGET_NET }}
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref_name }}

      - name: Extract target network from tag
        id: target_net
        env:
          TAG: ${{ github.ref_name }}
        run: |
          TARGET_NET=${TAG##desktop-wallet/*-}
          echo "TARGET_NET=$TARGET_NET" >> $GITHUB_OUTPUT

      - name: Verify tag version against project version
        id: version_check
        env:
          TAG: ${{ github.ref_name}}
        run: |
          # Extract version number
          VERSION=$(jq '.version' -r app/package.json)

          TAG_VERSION_NET=${TAG##*/}
          TAG_VERSION=${TAG_VERSION_NET%%-*}
          if [ "$VERSION" != "$TAG_VERSION" ]; then
            echo "::error:: Tag version is not correct. Tag version: $TAG_VERSION version from package.json: $VERSION"
            exit 1
          fi
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

  build:
    name: Build on ${{ matrix.platform.runner }}
    needs: metadata
    strategy:
      matrix:
        # For each platform provide the runner image to use and some unique id.
        platform:
          # - id: linux
          #   runner: ubuntu-latest
          # - id: windows
          #   runner: windows-2019
          # - id: macos-intel
          #   runner: macos-13
          - id: macos-arm64
            runner: macos-14
    runs-on: ${{ matrix.platform.runner }}
    env:
      # Set the target Concordium network.
      TARGET_NET: ${{ needs.metadata.outputs.TARGET_NET}}
      # Skip signing for Windows build.
      SIGNING: skip
      # Skip notarization for MacOS build.
      NOTARIZE: skip
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ref: ${{ github.ref_name }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          # Disable the default behavior of treating warnings as errors.
          # Should be removed again once the warnings are resolved.
          rustflags: ""

      - name: Setup wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: ${{ env.WASM-PACK_VERSION }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: List dependency versions
        run: |
          echo "::notice::node version: $(node --version)"
          echo "::notice::npm version: $(npm --version)"
          echo "::notice::yarn version: $(yarn --version)"
          echo "::notice::python version: $(python --version)"
          echo "::notice::rustup version: $(rustup show)"
          echo "::notice::wasm-pack version: $(wasm-pack --version)"

      - name: Install native packages (Ubuntu only)
        if: matrix.platform.id == 'linux'
        run: sudo apt-get install -y libusb-1.0 libudev-dev rpm

      - name: Install Node packages
        run: |
          corepack enable
          yarn

      - name: Build
        run: yarn package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.platform.id }}
          if-no-files-found: error
          path: |
            release/concordium-desktop-wallet-*
            release/latest*.yml

  upload-to-s3:
    name: Release to S3
    needs: [metadata, build]
    runs-on: ubuntu-latest
    environment: release
    env:
      AWS_ROLE_TO_ASSUME: "arn:aws:iam::192549843005:role/github_concordium-desktop-wallet"
      S3_BUCKET: "s3://desktopwallet.concordium.com"
    steps:
      - name: Assume role
        uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          aws-region: "eu-west-1"
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: ReleaseDesktopWalletSession
          mask-aws-account-id: false

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: false

      - name: Download artifacts
        uses: actions/download-artifact@v4
      - run: |
          mkdir uploads
          mv linux uploads/
          mv windows uploads/
          mv macos-intel uploads/
          mv macos-arm64 uploads/

      - name: Upload to S3 (dry-run)
        run: |
          TARGET_NET=${{ needs.metadata.outputs.TARGET_NET }}
          VERSION=${{ needs.metadata.outputs.VERSION }}
          S3_PATH="${{ env.S3_BUCKET }}/${VERSION}/${TARGET_NET}"
          echo "S3_PATH=$S3_PATH"

          # aws s3 cp\
          #     --recursive \
          #     --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers\
          #     upload/
          #     $S3_PATH

  # release:
  #   name: Attach to Github release
  #   needs: [metadata, build]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: write
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: recursive
  #     - uses: actions/download-artifact@v4
  #     - run: |
  #         mkdir uploads
  #         mv linux/concordium-desktop-wallet* uploads/
  #         mv win/concordium-desktop-wallet* uploads/
  #         mv mac-intel/concordium-desktop-wallet* uploads/
  #     # - name: Attach binaries to an existing release.
  #     #   env:
  #     #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #     #   run: |
  #     #     gh release upload ${{ github.ref_name }} uploads/*
