name: Concordium desktop wallet release

on:
  workflow_dispatch:
    inputs:
      service:
        type: choice
        description: Choose which workflow should be ran
        options:
          - desktop-wallet-windows
          - release-desktop-wallet-linux

  push:
    branches:
      - ekw/SRE-1001/release-desktop-wallet
    tags:
      - desktop-wallet-*/*

env:
  BASE_IMAGE_VERSION: "rust-1.82_ghc-9.6.6-1"
  STATIC_NODE_BINARY_IMAGE_NAME: 'static-node-binaries'
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::192549843005:role/github_concordium-desktop-wallet"
  S3_BUCKET: "s3://desktopwallet.concordium.com/"
  ECR_REPO: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/desktop-wallet-ci"

permissions:
  id-token: write
  contents: read

jobs:
  login-aws:
    runs-on: ubuntu-latest
    outputs:
      access_key: ${{ steps.export-creds.outputs.access_key }}
      secret_key: ${{ steps.export-creds.outputs.secret_key }}
      docker_username: ${{ steps.login-ecr.outputs.docker_username_ACCOUNT_ID_dkr_ecr_eu_west_1_amazonaws_com }}
      docker_password: ${{ steps.login-ecr.outputs.docker_password_ACCOUNT_ID_dkr_ecr_eu_west_1_amazonaws_com }}
    environment: release
    steps:
      - name: aws creds
        uses: aws-actions/configure-aws-credentials@v4
        id: creds
        with:
          aws-region: "eu-west-1"
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: ReleaseDesktopWalletSession
          output-credentials: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: false

      - name: Export creds
        id: export-creds
        run: |
          echo "access_key=$(echo ${{steps.creds.outputs.aws-access-key-id}} | base64 -w0 | base64 -w0 )" >> $GITHUB_OUTPUT
          echo "secret_key=$(echo ${{steps.creds.outputs.aws-secret-access-key}} | base64 -w0 | base64 -w0 )" >> $GITHUB_OUTPUT


  release-desktop-wallet-linux:
    environment: release
    needs: login-aws
    runs-on: ubuntu-latest
    container:
      image: "192549843005.dkr.ecr.eu-west-1.amazonaws.com/concordium/desktop-wallet-ci:latest"
      credentials:
        username: ${{needs.login-aws.outputs.docker_username}}
        password: ${{needs.login-aws.outputs.docker_password}}

    steps:
      - name: echo
        run: |
          node --version